apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: control-plane
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/anshulkamath/kube-testing.git
    targetRevision: HEAD
    path: deployments/helm/control-plane
  destination:
    name: kind
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
