apiVersion: v1
kind: Service
metadata:
  name: "{{ .Chart.Name }}-lb"
  namespace: {{ .Values.namespace }}
spec:
  selector:
    {{- include "control-plane.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: {{ .Values.externalPort }}
      targetPort: {{ .Values.controlPlanePort }}
  type: LoadBalancer
