apiVersion: v1
kind: Service
metadata:
  name: {{ include "control-plane.fullname" . }}
  labels:
    {{- include "control-plane.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "control-plane.selectorLabels" . | nindent 6 }}
  ports:
    - protocol: TCP
      port: {{ .Values.controlPlanePort }}
      targetPort: {{ .Values.controlPlanePort }}
  type: ClusterIP
