apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "workers.fullname" . }}
  labels:
    {{- include "workers.labels" . | nindent 4 }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "workers.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "workers.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.fqn }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.workerPort }}
          envFrom:
            - configMapRef:
                name: "{{ .Chart.Name }}-configmap"